FROM node:18-alpine

# Install Angular CLI globally
RUN npm install -g @angular/cli

WORKDIR /app

# Expose Angular's default port
EXPOSE 4200

# Keep the container running to allow for interactive development
CMD ["tail", "-f", "/dev/null"]
