apiVersion: apps/v1
kind: Deployment
metadata:
  name: morning-brew-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: morning-brew-backend
  template:
    metadata:
      labels:
        app: morning-brew-backend
    spec:
      containers:
      - name: morning-brew-backend
        image: <your-docker-registry>/morning-brew-backend:latest # Replace with your actual image
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: morning-brew-backend-service
spec:
  selector:
    app: morning-brew-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP