apiVersion: apps/v1
kind: Deployment
metadata:
  name: morning-brew-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: morning-brew-frontend
  template:
    metadata:
      labels:
        app: morning-brew-frontend
    spec:
      containers:
      - name: morning-brew-frontend
        image: <your-docker-registry>/morning-brew-frontend:latest # Replace with your actual image
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: morning-brew-frontend-service
spec:
  selector:
    app: morning-brew-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer